/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdminMembersRouteRouteImport } from './routes/dashboard/admin/members/route'
import { Route as DashboardAccountantVehiclesRouteRouteImport } from './routes/dashboard/accountant/vehicles/route'
import { Route as DashboardAccountantJournalEntriesRouteRouteImport } from './routes/dashboard/accountant/journal-entries/route'
import { Route as DashboardAccountantExpenseCategoriesRouteRouteImport } from './routes/dashboard/accountant/expense-categories/route'
import { Route as DashboardAccountantDriversRouteRouteImport } from './routes/dashboard/accountant/drivers/route'
import { Route as DashboardAccountantExpensesRouteRouteImport } from './routes/dashboard/accountant/expenses/route'
import { Route as DashboardAnalystAnalyticsIndexRouteImport } from './routes/dashboard/analyst/analytics/index'
import { Route as DashboardAdminMembersIndexRouteImport } from './routes/dashboard/admin/members/index'
import { Route as DashboardAccountantVehiclesIndexRouteImport } from './routes/dashboard/accountant/vehicles/index'
import { Route as DashboardAccountantJournalEntriesIndexRouteImport } from './routes/dashboard/accountant/journal-entries/index'
import { Route as DashboardAccountantExpenseCategoriesIndexRouteImport } from './routes/dashboard/accountant/expense-categories/index'
import { Route as DashboardAccountantDriversIndexRouteImport } from './routes/dashboard/accountant/drivers/index'
import { Route as DashboardAccountantExpensesIndexRouteImport } from './routes/dashboard/accountant/expenses/index'
import { Route as DashboardAnalystAnalyticsVehicleIdIndexRouteImport } from './routes/dashboard/analyst/analytics/$vehicleId/index'
import { Route as DashboardAccountantJournalEntriesNewIndexRouteImport } from './routes/dashboard/accountant/journal-entries/new/index'
import { Route as DashboardAccountantJournalEntriesEntryIdIndexRouteImport } from './routes/dashboard/accountant/journal-entries/$entryId/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminMembersRouteRoute =
  DashboardAdminMembersRouteRouteImport.update({
    id: '/admin/members',
    path: '/admin/members',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountantVehiclesRouteRoute =
  DashboardAccountantVehiclesRouteRouteImport.update({
    id: '/accountant/vehicles',
    path: '/accountant/vehicles',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountantJournalEntriesRouteRoute =
  DashboardAccountantJournalEntriesRouteRouteImport.update({
    id: '/accountant/journal-entries',
    path: '/accountant/journal-entries',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountantExpenseCategoriesRouteRoute =
  DashboardAccountantExpenseCategoriesRouteRouteImport.update({
    id: '/accountant/expense-categories',
    path: '/accountant/expense-categories',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountantDriversRouteRoute =
  DashboardAccountantDriversRouteRouteImport.update({
    id: '/accountant/drivers',
    path: '/accountant/drivers',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountantExpensesRouteRoute =
  DashboardAccountantExpensesRouteRouteImport.update({
    id: '/accountant/expenses',
    path: '/accountant/expenses',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAnalystAnalyticsIndexRoute =
  DashboardAnalystAnalyticsIndexRouteImport.update({
    id: '/analyst/analytics/',
    path: '/analyst/analytics/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAdminMembersIndexRoute =
  DashboardAdminMembersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdminMembersRouteRoute,
  } as any)
const DashboardAccountantVehiclesIndexRoute =
  DashboardAccountantVehiclesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAccountantVehiclesRouteRoute,
  } as any)
const DashboardAccountantJournalEntriesIndexRoute =
  DashboardAccountantJournalEntriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAccountantJournalEntriesRouteRoute,
  } as any)
const DashboardAccountantExpenseCategoriesIndexRoute =
  DashboardAccountantExpenseCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAccountantExpenseCategoriesRouteRoute,
  } as any)
const DashboardAccountantDriversIndexRoute =
  DashboardAccountantDriversIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAccountantDriversRouteRoute,
  } as any)
const DashboardAccountantExpensesIndexRoute =
  DashboardAccountantExpensesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAccountantExpensesRouteRoute,
  } as any)
const DashboardAnalystAnalyticsVehicleIdIndexRoute =
  DashboardAnalystAnalyticsVehicleIdIndexRouteImport.update({
    id: '/analyst/analytics/$vehicleId/',
    path: '/analyst/analytics/$vehicleId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountantJournalEntriesNewIndexRoute =
  DashboardAccountantJournalEntriesNewIndexRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => DashboardAccountantJournalEntriesRouteRoute,
  } as any)
const DashboardAccountantJournalEntriesEntryIdIndexRoute =
  DashboardAccountantJournalEntriesEntryIdIndexRouteImport.update({
    id: '/$entryId/',
    path: '/$entryId/',
    getParentRoute: () => DashboardAccountantJournalEntriesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/accountant/drivers': typeof DashboardAccountantDriversRouteRouteWithChildren
  '/dashboard/accountant/expense-categories': typeof DashboardAccountantExpenseCategoriesRouteRouteWithChildren
  '/dashboard/accountant/expenses': typeof DashboardAccountantExpensesRouteRouteWithChildren
  '/dashboard/accountant/journal-entries': typeof DashboardAccountantJournalEntriesRouteRouteWithChildren
  '/dashboard/accountant/vehicles': typeof DashboardAccountantVehiclesRouteRouteWithChildren
  '/dashboard/admin/members': typeof DashboardAdminMembersRouteRouteWithChildren
  '/dashboard/accountant/drivers/': typeof DashboardAccountantDriversIndexRoute
  '/dashboard/accountant/expense-categories/': typeof DashboardAccountantExpenseCategoriesIndexRoute
  '/dashboard/accountant/expenses/': typeof DashboardAccountantExpensesIndexRoute
  '/dashboard/accountant/journal-entries/': typeof DashboardAccountantJournalEntriesIndexRoute
  '/dashboard/accountant/vehicles/': typeof DashboardAccountantVehiclesIndexRoute
  '/dashboard/admin/members/': typeof DashboardAdminMembersIndexRoute
  '/dashboard/analyst/analytics/': typeof DashboardAnalystAnalyticsIndexRoute
  '/dashboard/accountant/journal-entries/$entryId/': typeof DashboardAccountantJournalEntriesEntryIdIndexRoute
  '/dashboard/accountant/journal-entries/new/': typeof DashboardAccountantJournalEntriesNewIndexRoute
  '/dashboard/analyst/analytics/$vehicleId/': typeof DashboardAnalystAnalyticsVehicleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/accountant/drivers': typeof DashboardAccountantDriversIndexRoute
  '/dashboard/accountant/expense-categories': typeof DashboardAccountantExpenseCategoriesIndexRoute
  '/dashboard/accountant/expenses': typeof DashboardAccountantExpensesIndexRoute
  '/dashboard/accountant/journal-entries': typeof DashboardAccountantJournalEntriesIndexRoute
  '/dashboard/accountant/vehicles': typeof DashboardAccountantVehiclesIndexRoute
  '/dashboard/admin/members': typeof DashboardAdminMembersIndexRoute
  '/dashboard/analyst/analytics': typeof DashboardAnalystAnalyticsIndexRoute
  '/dashboard/accountant/journal-entries/$entryId': typeof DashboardAccountantJournalEntriesEntryIdIndexRoute
  '/dashboard/accountant/journal-entries/new': typeof DashboardAccountantJournalEntriesNewIndexRoute
  '/dashboard/analyst/analytics/$vehicleId': typeof DashboardAnalystAnalyticsVehicleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/accountant/drivers': typeof DashboardAccountantDriversRouteRouteWithChildren
  '/dashboard/accountant/expense-categories': typeof DashboardAccountantExpenseCategoriesRouteRouteWithChildren
  '/dashboard/accountant/expenses': typeof DashboardAccountantExpensesRouteRouteWithChildren
  '/dashboard/accountant/journal-entries': typeof DashboardAccountantJournalEntriesRouteRouteWithChildren
  '/dashboard/accountant/vehicles': typeof DashboardAccountantVehiclesRouteRouteWithChildren
  '/dashboard/admin/members': typeof DashboardAdminMembersRouteRouteWithChildren
  '/dashboard/accountant/drivers/': typeof DashboardAccountantDriversIndexRoute
  '/dashboard/accountant/expense-categories/': typeof DashboardAccountantExpenseCategoriesIndexRoute
  '/dashboard/accountant/expenses/': typeof DashboardAccountantExpensesIndexRoute
  '/dashboard/accountant/journal-entries/': typeof DashboardAccountantJournalEntriesIndexRoute
  '/dashboard/accountant/vehicles/': typeof DashboardAccountantVehiclesIndexRoute
  '/dashboard/admin/members/': typeof DashboardAdminMembersIndexRoute
  '/dashboard/analyst/analytics/': typeof DashboardAnalystAnalyticsIndexRoute
  '/dashboard/accountant/journal-entries/$entryId/': typeof DashboardAccountantJournalEntriesEntryIdIndexRoute
  '/dashboard/accountant/journal-entries/new/': typeof DashboardAccountantJournalEntriesNewIndexRoute
  '/dashboard/analyst/analytics/$vehicleId/': typeof DashboardAnalystAnalyticsVehicleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/accountant/drivers'
    | '/dashboard/accountant/drivers'
    | '/dashboard/accountant/drivers'
    | '/dashboard/accountant/expense-categories'
    | '/dashboard/accountant/expenses'
    | '/dashboard/accountant/journal-entries'
    | '/dashboard/accountant/vehicles'
    | '/dashboard/admin/members'
    | '/dashboard/accountant/drivers/'
    | '/dashboard/accountant/drivers/'
    | '/dashboard/accountant/expense-categories/'
    | '/dashboard/accountant/expenses/'
    | '/dashboard/accountant/journal-entries/'
    | '/dashboard/accountant/vehicles/'
    | '/dashboard/admin/members/'
    | '/dashboard/analyst/analytics/'
    | '/dashboard/accountant/journal-entries/$entryId/'
    | '/dashboard/accountant/journal-entries/new/'
    | '/dashboard/analyst/analytics/$vehicleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/accountant/drivers'
    | '/dashboard/accountant/drivers'
    | '/dashboard/accountant/drivers'
    | '/dashboard/accountant/expense-categories'
    | '/dashboard/accountant/expenses'
    | '/dashboard/accountant/journal-entries'
    | '/dashboard/accountant/vehicles'
    | '/dashboard/admin/members'
    | '/dashboard/analyst/analytics'
    | '/dashboard/accountant/journal-entries/$entryId'
    | '/dashboard/accountant/journal-entries/new'
    | '/dashboard/analyst/analytics/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/accountant/drivers'
    | '/dashboard/accountant/drivers'
    | '/dashboard/accountant/drivers'
    | '/dashboard/accountant/expense-categories'
    | '/dashboard/accountant/expenses'
    | '/dashboard/accountant/journal-entries'
    | '/dashboard/accountant/vehicles'
    | '/dashboard/admin/members'
    | '/dashboard/accountant/drivers/'
    | '/dashboard/accountant/drivers/'
    | '/dashboard/accountant/expense-categories/'
    | '/dashboard/accountant/expenses/'
    | '/dashboard/accountant/journal-entries/'
    | '/dashboard/accountant/vehicles/'
    | '/dashboard/admin/members/'
    | '/dashboard/analyst/analytics/'
    | '/dashboard/accountant/journal-entries/$entryId/'
    | '/dashboard/accountant/journal-entries/new/'
    | '/dashboard/analyst/analytics/$vehicleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/members': {
      id: '/dashboard/admin/members'
      path: '/admin/members'
      fullPath: '/dashboard/admin/members'
      preLoaderRoute: typeof DashboardAdminMembersRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountant/vehicles': {
      id: '/dashboard/accountant/vehicles'
      path: '/accountant/vehicles'
      fullPath: '/dashboard/accountant/vehicles'
      preLoaderRoute: typeof DashboardAccountantVehiclesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountant/journal-entries': {
      id: '/dashboard/accountant/journal-entries'
      path: '/accountant/journal-entries'
      fullPath: '/dashboard/accountant/journal-entries'
      preLoaderRoute: typeof DashboardAccountantJournalEntriesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountant/drivers': {
      id: '/dashboard/accountant/drivers'
      path: '/accountant/drivers'
      fullPath: '/dashboard/accountant/drivers'
      preLoaderRoute: typeof DashboardAccountantDriversRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountant/expense-categories': {
      id: '/dashboard/accountant/expense-categories'
      path: '/accountant/expense-categories'
      fullPath: '/dashboard/accountant/expense-categories'
      preLoaderRoute: typeof DashboardAccountantExpenseCategoriesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountant/expenses': {
      id: '/dashboard/accountant/expenses'
      path: '/accountant/expenses'
      fullPath: '/dashboard/accountant/expenses'
      preLoaderRoute: typeof DashboardAccountantExpensesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analyst/analytics/': {
      id: '/dashboard/analyst/analytics/'
      path: '/analyst/analytics'
      fullPath: '/dashboard/analyst/analytics/'
      preLoaderRoute: typeof DashboardAnalystAnalyticsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/members/': {
      id: '/dashboard/admin/members/'
      path: '/'
      fullPath: '/dashboard/admin/members/'
      preLoaderRoute: typeof DashboardAdminMembersIndexRouteImport
      parentRoute: typeof DashboardAdminMembersRouteRoute
    }
    '/dashboard/accountant/vehicles/': {
      id: '/dashboard/accountant/vehicles/'
      path: '/'
      fullPath: '/dashboard/accountant/vehicles/'
      preLoaderRoute: typeof DashboardAccountantVehiclesIndexRouteImport
      parentRoute: typeof DashboardAccountantVehiclesRouteRoute
    }
    '/dashboard/accountant/journal-entries/': {
      id: '/dashboard/accountant/journal-entries/'
      path: '/'
      fullPath: '/dashboard/accountant/journal-entries/'
      preLoaderRoute: typeof DashboardAccountantJournalEntriesIndexRouteImport
      parentRoute: typeof DashboardAccountantJournalEntriesRouteRoute
    }
    '/dashboard/accountant/drivers/': {
      id: '/dashboard/accountant/drivers/'
      path: '/'
      fullPath: '/dashboard/accountant/drivers/'
      preLoaderRoute: typeof DashboardAccountantDriversIndexRouteImport
      parentRoute: typeof DashboardAccountantDriversRouteRoute
    }
    '/dashboard/accountant/expense-categories/': {
      id: '/dashboard/accountant/expense-categories/'
      path: '/'
      fullPath: '/dashboard/accountant/expense-categories/'
      preLoaderRoute: typeof DashboardAccountantExpenseCategoriesIndexRouteImport
      parentRoute: typeof DashboardAccountantExpenseCategoriesRouteRoute
    }
    '/dashboard/accountant/expenses/': {
      id: '/dashboard/accountant/expenses/'
      path: '/'
      fullPath: '/dashboard/accountant/expenses/'
      preLoaderRoute: typeof DashboardAccountantExpensesIndexRouteImport
      parentRoute: typeof DashboardAccountantExpensesRouteRoute
    }
    '/dashboard/analyst/analytics/$vehicleId/': {
      id: '/dashboard/analyst/analytics/$vehicleId/'
      path: '/analyst/analytics/$vehicleId'
      fullPath: '/dashboard/analyst/analytics/$vehicleId/'
      preLoaderRoute: typeof DashboardAnalystAnalyticsVehicleIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accountant/journal-entries/new/': {
      id: '/dashboard/accountant/journal-entries/new/'
      path: '/new'
      fullPath: '/dashboard/accountant/journal-entries/new/'
      preLoaderRoute: typeof DashboardAccountantJournalEntriesNewIndexRouteImport
      parentRoute: typeof DashboardAccountantJournalEntriesRouteRoute
    }
    '/dashboard/accountant/journal-entries/$entryId/': {
      id: '/dashboard/accountant/journal-entries/$entryId/'
      path: '/$entryId'
      fullPath: '/dashboard/accountant/journal-entries/$entryId/'
      preLoaderRoute: typeof DashboardAccountantJournalEntriesEntryIdIndexRouteImport
      parentRoute: typeof DashboardAccountantJournalEntriesRouteRoute
    }
  }
}

interface DashboardAccountantExpenseCategoriesRouteRouteChildren {
  DashboardAccountantExpenseCategoriesIndexRoute: typeof DashboardAccountantExpenseCategoriesIndexRoute
}
interface DashboardAccountantDriversRouteRouteChildren {
  DashboardAccountantDriversIndexRoute: typeof DashboardAccountantDriversIndexRoute
}
interface DashboardAccountantExpensesRouteRouteChildren {
  DashboardAccountantExpensesIndexRoute: typeof DashboardAccountantExpensesIndexRoute
}

const DashboardAccountantExpenseCategoriesRouteRouteChildren: DashboardAccountantExpenseCategoriesRouteRouteChildren =
  {
    DashboardAccountantExpenseCategoriesIndexRoute:
      DashboardAccountantExpenseCategoriesIndexRoute,
  }
const DashboardAccountantDriversRouteRouteChildren: DashboardAccountantDriversRouteRouteChildren =
  {
    DashboardAccountantDriversIndexRoute: DashboardAccountantDriversIndexRoute,
  }
const DashboardAccountantExpensesRouteRouteChildren: DashboardAccountantExpensesRouteRouteChildren =
  {
    DashboardAccountantExpensesIndexRoute: DashboardAccountantExpensesIndexRoute,
  }

const DashboardAccountantExpenseCategoriesRouteRouteWithChildren =
  DashboardAccountantExpenseCategoriesRouteRoute._addFileChildren(
    DashboardAccountantExpenseCategoriesRouteRouteChildren,
  )
const DashboardAccountantDriversRouteRouteWithChildren =
  DashboardAccountantDriversRouteRoute._addFileChildren(
    DashboardAccountantDriversRouteRouteChildren,
  )
const DashboardAccountantExpensesRouteRouteWithChildren =
  DashboardAccountantExpensesRouteRoute._addFileChildren(
    DashboardAccountantExpensesRouteRouteChildren,
  )

interface DashboardAccountantJournalEntriesRouteRouteChildren {
  DashboardAccountantJournalEntriesIndexRoute: typeof DashboardAccountantJournalEntriesIndexRoute
  DashboardAccountantJournalEntriesEntryIdIndexRoute: typeof DashboardAccountantJournalEntriesEntryIdIndexRoute
  DashboardAccountantJournalEntriesNewIndexRoute: typeof DashboardAccountantJournalEntriesNewIndexRoute
}

const DashboardAccountantJournalEntriesRouteRouteChildren: DashboardAccountantJournalEntriesRouteRouteChildren =
  {
    DashboardAccountantJournalEntriesIndexRoute:
      DashboardAccountantJournalEntriesIndexRoute,
    DashboardAccountantJournalEntriesEntryIdIndexRoute:
      DashboardAccountantJournalEntriesEntryIdIndexRoute,
    DashboardAccountantJournalEntriesNewIndexRoute:
      DashboardAccountantJournalEntriesNewIndexRoute,
  }

const DashboardAccountantJournalEntriesRouteRouteWithChildren =
  DashboardAccountantJournalEntriesRouteRoute._addFileChildren(
    DashboardAccountantJournalEntriesRouteRouteChildren,
  )

interface DashboardAccountantVehiclesRouteRouteChildren {
  DashboardAccountantVehiclesIndexRoute: typeof DashboardAccountantVehiclesIndexRoute
}

const DashboardAccountantVehiclesRouteRouteChildren: DashboardAccountantVehiclesRouteRouteChildren =
  {
    DashboardAccountantVehiclesIndexRoute:
      DashboardAccountantVehiclesIndexRoute,
  }

const DashboardAccountantVehiclesRouteRouteWithChildren =
  DashboardAccountantVehiclesRouteRoute._addFileChildren(
    DashboardAccountantVehiclesRouteRouteChildren,
  )

interface DashboardAdminMembersRouteRouteChildren {
  DashboardAdminMembersIndexRoute: typeof DashboardAdminMembersIndexRoute
}

const DashboardAdminMembersRouteRouteChildren: DashboardAdminMembersRouteRouteChildren =
  {
    DashboardAdminMembersIndexRoute: DashboardAdminMembersIndexRoute,
  }

const DashboardAdminMembersRouteRouteWithChildren =
  DashboardAdminMembersRouteRoute._addFileChildren(
    DashboardAdminMembersRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountantDriversRouteRoute: typeof DashboardAccountantDriversRouteRouteWithChildren
  DashboardAccountantExpenseCategoriesRouteRoute: typeof DashboardAccountantExpenseCategoriesRouteRouteWithChildren
  DashboardAccountantExpensesRouteRoute: typeof DashboardAccountantExpensesRouteRouteWithChildren
  DashboardAccountantJournalEntriesRouteRoute: typeof DashboardAccountantJournalEntriesRouteRouteWithChildren
  DashboardAccountantVehiclesRouteRoute: typeof DashboardAccountantVehiclesRouteRouteWithChildren
  DashboardAdminMembersRouteRoute: typeof DashboardAdminMembersRouteRouteWithChildren
  DashboardAnalystAnalyticsIndexRoute: typeof DashboardAnalystAnalyticsIndexRoute
  DashboardAnalystAnalyticsVehicleIdIndexRoute: typeof DashboardAnalystAnalyticsVehicleIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountantDriversRouteRoute:
    DashboardAccountantDriversRouteRouteWithChildren,
  DashboardAccountantExpenseCategoriesRouteRoute:
    DashboardAccountantExpenseCategoriesRouteRouteWithChildren,
  DashboardAccountantExpensesRouteRoute:
    DashboardAccountantExpensesRouteRouteWithChildren,
  DashboardAccountantJournalEntriesRouteRoute:
    DashboardAccountantJournalEntriesRouteRouteWithChildren,
  DashboardAccountantVehiclesRouteRoute:
    DashboardAccountantVehiclesRouteRouteWithChildren,
  DashboardAdminMembersRouteRoute: DashboardAdminMembersRouteRouteWithChildren,
  DashboardAnalystAnalyticsIndexRoute: DashboardAnalystAnalyticsIndexRoute,
  DashboardAnalystAnalyticsVehicleIdIndexRoute:
    DashboardAnalystAnalyticsVehicleIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
